apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers: 
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: contents-vol
          readOnly: true
    - name: cloner
      image: jhg7856/c-clone:0.2
      env:
        - name: CONTENTS_SOURCE_URL
          value: "https://github.com/jaden7856/web-contents.git"
      volumeMounts:
        - mountPath: /data
          name: contents-vol
  volumes:
    - name: contents-vol
      emptyDir: {}
